### ISSUE TITLE
feat: request queue 구현

### ISSUE THREAD

**Issue by nannahy** [nannahy/frontend-test#13]
## 문제
클래스로 구현된 request queue를 custom hook으로 변경하려 하는데, 두 부분에서 해결방법을 찾지 못했습니다.
1. addTask 함수를 통해 queue에 task를 넣을 수 있으나, 요청이 끝난 후 결과값이 나온 시점을 어떻게 알 수 있는가?
    > 기존에는 enqueue.then~~ 등으로 요청함수의 반환값에 결과를 넣어주는 식으로 작성했으나,  
현재는 task를 state로 관리하고, 요청을 useEffect에서 처리하는 방식이어서 관리가 어려움
2. 훅의 특성상 컴포넌트 내에서 사용해야하는데, 여러 위젯에서 각각 선언되므로 중앙 통제가 어려움
    > App.tsx에서 queue를 선언하고, widget으로 넘겨주는 방법 외에 마땅한 방법이 생각나지 않는데, 이 역시 좋은 방법은 아닌 것 같습니다...

```javascript
function useTaskQueue(): any {
  const [queue, setQueue] = useState({ isProcessing: false, tasks: [] });  // 들어온 task 리스트
  const [response, setResponse] = useState();  // 결과값

  useEffect(() => {
    if (!queue.tasks.length) return;
    if (queue.isProcessing) return;

    const task = queue.tasks[0];
    setQueue((prev) => ({
      isProcessing: true,
      tasks: prev.tasks.slice(1),
    }));

    async function doTask() {
      const response = await (await task()).json();
      try {
        setResponse(response);
      } catch (e) {
        console.log(e);
      } finally {
        setQueue((prev) => ({
          isProcessing: false,
          tasks: prev.tasks,
        }));
      }
    }

    doTask();
  }, [queue]);

  const addTask = useCallback((task) => {
    setQueue((prev) => ({
      isProcessing: prev.isProcessing,
      tasks: [...prev.tasks, task],
    }));
  }, []);

  return {
    tasks: queue.tasks,
    isProcessing: queue.isProcessing,
    addTask,
  };
}
```

**Comment by swlee93** [comment]
1. addTask 함수를 통해 queue에 task를 넣을 수 있으나, 요청이 끝난 후 결과값이 나온 시점을 어떻게 알 수 있는가?
  (1) 위젯에서 addTask (enqueue)
  (2) useTaskQueue에서 일정 주기로 queue에 쌓인 task를 처리하고 queue 비우기 (dequeue)
       - useEffect(() => , [queue]) 대신 Timeout을 재귀적으로 호출해서 queue 상태를 체크
       - useState() 로 선언된 request,response는 하위의 모든 위젯이 업데이트될 때 마다 전체 컴포넌트에 렌더를 유발합니다. -> useRef 로 대체하고, 전체 request 해소 시 setRequestState를 통해 렌더 트리거

2. 훅의 특성상 컴포넌트 내에서 사용해야하는데, 여러 위젯에서 각각 선언되므로 중앙 통제가 어려움
       - context 또는 redux 사용을 고민해볼 때 인것 같습니다. 아래 예시에선 context를 사용했는데요, 유지보수 차원에서 관리가 편한 context 사용도 나쁘지 않습니다. 아래 아티클을 한 번 읽어보세요! 
       - https://olaf-go.medium.com/context-api-vs-redux-e8a53df99b8
       - https://kentcdodds.com/blog/how-to-use-react-context-effectively

// 예시 : sudo 코드입니다. 참고만 부탁드려요 
const RequestApiController = () => {
  const [requestState, setRequestState] = useState({
    fetchedEndTime: 0,
  });
 
  const requestQueue = useRef({});
  const responseData = useRef({});

  const addRequestApi = (request) => {
    requestQueue.current[request.id] = request.api
  };

  const recursiveTimeoutRef = useRef<NodeJS.Timeout>();
  useEffect(() => {
    const retrieveSynchronously = async (requests, response) => {
      await Object.entries(requests)
        .reduce(async (prev, currentRequest)) => {
          await prev;
          await doTask(currentRequest)
              .finally((currentResponse) => {
                   responseData.current[currentRequest.id] = currentResponse;
              });
          }
        }, Promise.resolve())
        
        .finally(() => {
           // 렌더 조건 업데이트
          setRequestState({ fetchedEndTime: Date.now() });
        });

      if (recursiveTimeoutRef?.current) {
        clearTimeout(recursiveTimeoutRef?.current);
      }
      // 재귀 호출
      recursiveTimeoutRef.current = setTimeout(() => {
        retrieveSynchronously(requestQueue.current, responseData.current);
      }, 1000);
    };

    // 즉시 호출
    retrieveSynchronously(requestQueue.current, responseData.current);

    return () => {
      // 언마운트 시
      if (recursiveTimeoutRef.current) {
        clearTimeout(recursiveTimeoutRef.current);
      }
    };
  }, []);

  return (
    <RequestApiControllerContext.Provider
      value={{
        addRequestApi,
        requestState,
        responseData,
      }}
    >
      {children}
    </RequestApiControllerContext.Provider>
  );
};
